artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "C:/Users/Omar/Desktop/Omar_Files/Python_Analysis/EndToEndMachineLearningProjectAutoMobilePrice/new_cleaned_df.csv"
  local_data_file: artifacts/data_ingestion/data.csv


data_validation:
  root_dir: artifacts/data_validation
  data_path: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation  
  data_path: artifacts/data_ingestion/data.csv


training:
  root_dir: artifacts/training
  train_data_path : artifacts/data_transformation/train.csv
  test_data_path : artifacts/data_transformation/test.csv
  model_name: model.joblib  


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path : artifacts/data_transformation/test.csv
  model_path: artifacts/training/model.joblib
  metrics_file_name: artifacts/model_evaluation/metrics.json
  