artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: new_cleaned_df.csv
  local_data_file: artifacts/data_ingestion/data.csv
  train_data_path: artifacts/data_ingestion/train_data.csv
  test_data_path: artifacts/data_ingestion/test_data.csv



prepare_base_model:
  root_dir: artifacts/prepare_base_model  
  base_model_path: artifacts/prepare_base_model/preprocessor.pkl
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.pkl
  train_data_path: artifacts/prepare_base_model/train_data
  test_data_path: artifacts/prepare_base_model/test_data


training:
  root_dir: artifacts/training
  trained_model_file_path: artifacts/training/model.pkl


model_evaluation:
    root_dir: artifacts/model_evaluation 
    model_path: artifacts/prepare_base_model/preprocessor.pkl
    metrix_file_name: artifacts/model_evaluation/metrix.json
    training_data: artifacts/prepare_base_model/train_data
    testing_data: artifacts/prepare_base_model/test_data
  